services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - keycloak-data:/opt/keycloak/data
    command: ["start-dev"]

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.34.0
    container_name: azurite
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service
    volumes:
      - azurite-data:/data

  # postgres:
  #   image: postgres:17.4
  #   container_name: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  # pgAdminBootCamp:
  #   depends_on:
  #     - postgres
  #   image: dpage/pgadmin4:8.6
  #   container_name: pgAdmin-dev-bootcamp
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   ports:
  #     - "5050:80"
  #   environment:
  #     - PGADMIN_DEFAULT_PASSWORD=123456
  #     - PGADMIN_DEFAULT_EMAIL=superman@google.com
  #   restart: always

  # gamestore-api:
  #   image: gamestore-api:1.4
  #   container_name: gamestore-api
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: Development
  #     ConnectionStrings__GameStoreDB: "Host=postgres;Port=5432;Username=postgres;Database=gamestore"
  #     ConnectionStrings__Blobs: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;"
  #   ports:
  #     - "5100:8080"
volumes:
  keycloak-data:
  azurite-data:
  postgres-data:
  pgadmin-data:
